#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

# TODO: Add check to see what kind of monitors are connected and configure UI accordingly
# TODO: multimonitor support
# TODO: multiresolution support

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Set monitor layout
bspc monitor -d I II III IV V VI VII VIII IX X

# Configure gaps and borders
bspc config border_width 2
bspc config window_gap 4

# Border theme: chaOS
bspc config focused_border_color "#E6007A"
bspc config normal_border_color "#800341"
bspc config active_border_color "#FA0079"

# Configure window rules
bspc config split_ratio 0.53
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Peek state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#
# Autostart
#
# Start clipboard manager
greenclip daemon &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/ &
# Picom
# picom -b &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
# Wallpaper
feh --bg-scale /usr/share/chaos/backgrounds/chaOS.webp
